# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: |
            sudo apt-get update
            sudo apt-get install -y --no-install-recommends build-essential
            sudo apt-get install -y texlive-xetex unzip wget git
            sudo apt-get install -y python3 python3-pip
            pip3 install -U pip setuptools
            pip3 install sphinx sphinx-autobuild sphinx_rtd_theme rst2pdf
            sudo wget "http://mirrors.ctan.org/fonts/fandol.zip" -O /usr/share/fonts/fandol.zip
            sudo unzip /usr/share/fonts/fandol.zip -d /usr/share/fonts
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Build Document
        run: |
            git fetch --prune --unshallow
            cd ./doc/developer_manual
            make html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload html
          path: './doc/developer_manual/html/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
