# check the pull-request document
name: check Pages

on:
  # Runs on pushes targeting the default branch
  pull_request:
    branches: ["master"]
    paths:
      - 'doc/**'

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: |
            sudo apt-get update
            sudo apt-get install -y --no-install-recommends build-essential
            sudo apt-get install -y texlive-xetex unzip wget git
            sudo apt-get install -y python3 python3-pip
            pip3 install -U pip setuptools
            pip3 install sphinx sphinx-autobuild sphinx_rtd_theme rst2pdf
            sudo wget "http://mirrors.ctan.org/fonts/fandol.zip" -O /usr/share/fonts/fandol.zip
            sudo unzip /usr/share/fonts/fandol.zip -d /usr/share/fonts
      - name: Checkout
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: Build Document
        run: |
            cd ./doc/developer_manual
            make html
